#!/usr/bin/env bash
# Environment setting launcher for classic confinement snaps
# This launcher gives priority to in-snap external command and library searching, making classic confinement snaps behave "like" strict confinement snaps.  This launcher should be dropped if the snap isn't in classic confinement.
# This launcher depend on the workaround-snap-arch-triplet remote part, run the `workaround-snap-arch-triplet-launch` launcher before this launcher
# https://github.com/Lin-Buo-Ren/snap-arch-triplet-part
# 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com> © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

if ! test -v SNAP_ARCH_TRIPLET; then
    printf -- \
        'classic-launch: Error: Packaging bug!  Please run `workaround-snap-arch-triplet-launch` before `classic launch`!\n' \
        1>&2
    exit 1
fi

PATH="$SNAP"/usr/sbin:"$SNAP"/usr/bin:"$SNAP"/sbin:"$SNAP"/bin:"$PATH"

if test -v LD_LIBRARY_PATH; then
	LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"$SNAP"/lib:"$SNAP"/usr/lib:"$SNAP"/lib/"${SNAP_ARCH_TRIPLET}":"$SNAP"/usr/lib/"${SNAP_ARCH_TRIPLET}":"$SNAP"/usr/lib/"${SNAP_ARCH_TRIPLET}"/mesa:"$SNAP"/usr/lib/"${SNAP_ARCH_TRIPLET}"/mesa-egl
else
	LD_LIBRARY_PATH="$SNAP"/lib:"$SNAP"/usr/lib:"$SNAP"/lib/"${SNAP_ARCH_TRIPLET}":"$SNAP"/usr/lib/"${SNAP_ARCH_TRIPLET}":"$SNAP"/usr/lib/"${SNAP_ARCH_TRIPLET}"/mesa:"$SNAP"/usr/lib/"${SNAP_ARCH_TRIPLET}"/mesa-egl
	export LD_LIBRARY_PATH
fi
LD_LIBRARY_PATH="$SNAP_LIBRARY_PATH":"$LD_LIBRARY_PATH"

exec "${@}"
