#!/usr/bin/env bash
# This is a launcher for demonstrative purpose, it may be dropped if not used.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

# Make necessary runtime changes to make the snap work
#export IMPORTANT_ENVIRONMENT_VARIABLE=value

# Finally run the launching command
#my-app-command
